---
- name: install packages from variable (ver 2, local)

  vars:
    packages:
      - mc
      - wget
      - epel-release
      - vim
      - bash-completion
      - bash-completion-extras


  hosts: test

  gather_facts: False

  tasks:

  - name: install packages from variable
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"

