---
- name: disable all traffic but 22, 80, 443 TCP, ICMP

  hosts: test

  gather_facts: False

  tasks:

  - name: install iptables-services
    yum:
      name: iptables-services
      state: present

  - name: copy config file
    copy:
      src: files/iptables
      dest: /etc/sysconfig/
      mode: 0600


  - name: start and enable iptables service
    service:
      name: iptables
      state: started
      enabled: true
